export type Prospecto = {
  id: number;
  nombre_empresa: string;
  persona_contacto?: string;
  cargo?: string;
  email?: string;
  telefono?: string;
  web?: string;
  linkedin?: string;
  sector?: string;
  ciudad?: string;
  pais?: string;
  fase?: 'Prospecto' | 'Contactado' | 'Propuesta' | 'Negociacion' | 'Cerrado' | 'Descartado';
  prioridad?: 'Alta' | 'Media' | 'Baja';
  origen?: string;
  notas?: string;
  ultimo_contacto?: string;
  proximo_seguimiento?: string;
  valor_estimado?: number;
  estado?: 'No contactado' | 'M1 enviado' | 'M2 enviado' | 'M3 enviado' | 'Respuesta' | 'Cita agendada' | 'Descartado';
  created_at?: string;
  updated_at?: string;
};
